// This file is auto-generated by @hey-api/openapi-ts

export type GetApiExhibitionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/exhibitions';
};

export type GetApiExhibitionsResponses = {
    200: {
        exhibitions: Array<{
            description: string | unknown;
            endDate: string;
            id: number;
            image: string;
            shortDescription: string | unknown;
            startDate: string;
            title: string;
            venue: {
                address1: string | unknown;
                city: string | unknown;
                country: string | unknown;
                fullname: string;
                id: number;
                name: string;
                state: string | unknown;
            };
            venueId: number;
        }>;
    };
};

export type GetApiExhibitionsResponse = GetApiExhibitionsResponses[keyof GetApiExhibitionsResponses];

export type GetApiExhibitionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/exhibitions/{id}';
};

export type GetApiExhibitionsByIdResponses = {
    200: {
        exhibition: {
            description: string | unknown;
            endDate: string;
            id: number;
            image: string;
            shortDescription: string | unknown;
            startDate: string;
            title: string;
            venue: {
                address1: string | unknown;
                city: string | unknown;
                country: string | unknown;
                fullname: string;
                id: number;
                name: string;
                state: string | unknown;
            };
            venueId: number;
        };
    };
};

export type GetApiExhibitionsByIdResponse = GetApiExhibitionsByIdResponses[keyof GetApiExhibitionsByIdResponses];

export type ClientOptions = {
    baseUrl: 'https://artscape.4each.org' | 'http://localhost:8080' | (string & {});
};